// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoApiLogon {
	
	
	// Base type probably should be MonoTouch.Foundation.NSObject or subclass
	[MonoTouch.Foundation.Register("AppDelegateIPhone")]
	public partial class AppDelegateIPhone {
		
		private MonoTouch.UIKit.UIWindow __mt_window;
		
		private MonoTouch.UIKit.UIButton __mt_buttonGo;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("window")]
		private MonoTouch.UIKit.UIWindow window {
			get {
				this.__mt_window = ((MonoTouch.UIKit.UIWindow)(this.GetNativeField("window")));
				return this.__mt_window;
			}
			set {
				this.__mt_window = value;
				this.SetNativeField("window", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("buttonGo")]
		private MonoTouch.UIKit.UIButton buttonGo {
			get {
				this.__mt_buttonGo = ((MonoTouch.UIKit.UIButton)(this.GetNativeField("buttonGo")));
				return this.__mt_buttonGo;
			}
			set {
				this.__mt_buttonGo = value;
				this.SetNativeField("buttonGo", value);
			}
		}
	}
}
